/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 17
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 14
#define ALIAS_COUNT 0
#define TOKEN_COUNT 5
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym__statement_line_token1 = 1,
  anon_sym_GT_GT_GT = 2,
  anon_sym_DOT_DOT_DOT = 3,
  sym__text = 4,
  sym_docstring = 5,
  sym_statement = 6,
  sym__statement_line = 7,
  sym__statement_line_continued = 8,
  sym__prompt = 9,
  sym__prompt_contd = 10,
  sym_statement_content = 11,
  sym_statement_result = 12,
  aux_sym_statement_repeat1 = 13,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__statement_line_token1] = "_statement_line_token1",
  [anon_sym_GT_GT_GT] = ">>>",
  [anon_sym_DOT_DOT_DOT] = "...",
  [sym__text] = "_text",
  [sym_docstring] = "docstring",
  [sym_statement] = "statement",
  [sym__statement_line] = "_statement_line",
  [sym__statement_line_continued] = "_statement_line_continued",
  [sym__prompt] = "_prompt",
  [sym__prompt_contd] = "_prompt_contd",
  [sym_statement_content] = "statement_content",
  [sym_statement_result] = "statement_result",
  [aux_sym_statement_repeat1] = "statement_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__statement_line_token1] = aux_sym__statement_line_token1,
  [anon_sym_GT_GT_GT] = anon_sym_GT_GT_GT,
  [anon_sym_DOT_DOT_DOT] = anon_sym_DOT_DOT_DOT,
  [sym__text] = sym__text,
  [sym_docstring] = sym_docstring,
  [sym_statement] = sym_statement,
  [sym__statement_line] = sym__statement_line,
  [sym__statement_line_continued] = sym__statement_line_continued,
  [sym__prompt] = sym__prompt,
  [sym__prompt_contd] = sym__prompt_contd,
  [sym_statement_content] = sym_statement_content,
  [sym_statement_result] = sym_statement_result,
  [aux_sym_statement_repeat1] = aux_sym_statement_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__statement_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym_docstring] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__statement_line] = {
    .visible = false,
    .named = true,
  },
  [sym__statement_line_continued] = {
    .visible = false,
    .named = true,
  },
  [sym__prompt] = {
    .visible = false,
    .named = true,
  },
  [sym__prompt_contd] = {
    .visible = false,
    .named = true,
  },
  [sym_statement_content] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_result] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == '>') ADVANCE(17);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(0);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == '>') ADVANCE(17);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(3);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(17);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(4);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(5);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym__statement_line_token1);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(1);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_GT_GT_GT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_DOT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == '>') ADVANCE(17);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(3);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(19);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '.') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(19);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '>') ADVANCE(17);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(4);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '>') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(19);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '>') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(19);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(5);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym__text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(19);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_GT_GT_GT] = ACTIONS(1),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(1),
    [sym__text] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_docstring] = STATE(10),
    [sym_statement] = STATE(9),
    [sym__statement_line] = STATE(2),
    [sym__prompt] = STATE(7),
    [anon_sym_GT_GT_GT] = ACTIONS(3),
    [sym__text] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(11), 1,
      sym__text,
    STATE(8), 1,
      sym__prompt_contd,
    STATE(12), 1,
      sym_statement_result,
    STATE(3), 2,
      sym__statement_line_continued,
      aux_sym_statement_repeat1,
  [20] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(11), 1,
      sym__text,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      sym__prompt_contd,
    STATE(16), 1,
      sym_statement_result,
    STATE(4), 2,
      sym__statement_line_continued,
      aux_sym_statement_repeat1,
  [40] = 5,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(20), 1,
      sym__text,
    STATE(8), 1,
      sym__prompt_contd,
    STATE(4), 2,
      sym__statement_line_continued,
      aux_sym_statement_repeat1,
  [57] = 2,
    ACTIONS(22), 1,
      ts_builtin_sym_end,
    ACTIONS(24), 2,
      anon_sym_DOT_DOT_DOT,
      sym__text,
  [65] = 2,
    ACTIONS(26), 1,
      ts_builtin_sym_end,
    ACTIONS(28), 2,
      anon_sym_DOT_DOT_DOT,
      sym__text,
  [73] = 2,
    ACTIONS(30), 1,
      sym__text,
    STATE(14), 1,
      sym_statement_content,
  [80] = 2,
    ACTIONS(30), 1,
      sym__text,
    STATE(15), 1,
      sym_statement_content,
  [87] = 1,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
  [91] = 1,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
  [95] = 1,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
  [99] = 1,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
  [103] = 1,
    ACTIONS(38), 1,
      aux_sym__statement_line_token1,
  [107] = 1,
    ACTIONS(40), 1,
      aux_sym__statement_line_token1,
  [111] = 1,
    ACTIONS(42), 1,
      aux_sym__statement_line_token1,
  [115] = 1,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 20,
  [SMALL_STATE(4)] = 40,
  [SMALL_STATE(5)] = 57,
  [SMALL_STATE(6)] = 65,
  [SMALL_STATE(7)] = 73,
  [SMALL_STATE(8)] = 80,
  [SMALL_STATE(9)] = 87,
  [SMALL_STATE(10)] = 91,
  [SMALL_STATE(11)] = 95,
  [SMALL_STATE(12)] = 99,
  [SMALL_STATE(13)] = 103,
  [SMALL_STATE(14)] = 107,
  [SMALL_STATE(15)] = 111,
  [SMALL_STATE(16)] = 115,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_statement_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [20] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_statement_repeat1, 2, 0, 0),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_line, 3, 0, 0),
  [24] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_line, 3, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_line_continued, 3, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_line_continued, 3, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_docstring, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_result, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_content, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pydoc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
